# Generated by Django 5.2.8 on 2026-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('designation', models.CharField(max_length=200)),
                ('qualifications', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField()),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('consultation_information', models.TextField(blank=True)),
                ('research', models.TextField(blank=True)),
                ('memberships', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospitals', models.ManyToManyField(blank=True, to='doctors.hospital')),
                ('specialities', models.ManyToManyField(blank=True, to='doctors.speciality')),
                ('treatments', models.ManyToManyField(blank=True, to='doctors.treatment')),
            ],
        ),
    ]
